server:
  contextPath: /gdo/api
  tomcat.base-dir: tmp

spring:
  redshiftdatasource:
    driverClassName: com.amazon.redshift.jdbc41.Driver
    jdbcUrl: jdbc:redshift://test
    username: test
    password: test
  maindatasource:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  jackson.serialization.write_dates_as_timestamps: false

logging:
  path: tmp/logs
  level.com.cadreon: DEBUG

gdo:
  websocket.push.interval: 1000
  report.sync.interval: 600000

---

spring:
  profiles: embedded
  maindatasource:
      driverClassName: org.h2.Driver
      jdbcUrl: jdbc:h2:test
      username: gdo_user
      password:
